name: Publish @credenza3/partner-sdk

# Controls when the workflow will run
on:
  push:
    branches: [main]
    paths:
      - 'package.json'
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: read   # Required for actions/checkout    

jobs:
  publish-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          scope: '@credenza3'
      - uses: pnpm/action-setup@v4
        with:
          version: latest   
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      #- name: Tests
      #  run: pnpm run test
      - name: Build package
        run: pnpm run build
      - name: Publish package
        run: pnpm publish --access public --no-git-checks
